# Generated by Django 3.2.9 on 2022-02-19 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elon',
            name='elon_id',
        ),
    ]
