# Generated by Django 4.0.2 on 2022-02-20 15:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elon',
            old_name='cr_on',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='elon',
            name='CPU',
        ),
        migrations.RemoveField(
            model_name='elon',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='elon',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='elon',
            name='display',
        ),
        migrations.RemoveField(
            model_name='elon',
            name='elon_id',
        ),
        migrations.RemoveField(
            model_name='elon',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='elon',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='elon',
            name='zaryad',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lang',
        ),
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elon',
            name='step',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Mobil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('memory', models.IntegerField(blank=True, default=0, null=True)),
                ('CPU', models.IntegerField(blank=True, default=0, null=True)),
                ('camera', models.CharField(blank=True, max_length=20, null=True)),
                ('zaryad', models.CharField(blank=True, max_length=20, null=True)),
                ('condition', models.CharField(blank=True, max_length=30, null=True)),
                ('display', models.CharField(blank=True, max_length=20, null=True)),
                ('processor', models.CharField(blank=True, max_length=30, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('step', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bot.user')),
            ],
        ),
    ]
