# Generated by Django 3.2.6 on 2022-02-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0002_auto_20220202_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elon',
            name='journey',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
