# Generated by Django 3.2.6 on 2022-02-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0003_alter_elon_journey'),
    ]

    operations = [
        migrations.AddField(
            model_name='elon',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='elon',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
