# Generated by Django 3.2.9 on 2022-02-16 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0005_alter_elon_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='elon',
            name='elon_id',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='elon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='elon',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='elon',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='elon',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Bot.category'),
        ),
    ]
