# Generated by Django 3.2.9 on 2022-02-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0010_auto_20220218_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
