# Generated by Django 3.2.9 on 2022-02-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0014_auto_20220219_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elon',
            name='elon_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
