# Generated by Django 3.2.9 on 2022-02-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0015_auto_20220219_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elon',
            name='elon_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.BigIntegerField(default=0, unique=True),
        ),
    ]
